# Generated by Django 4.2.14 on 2024-07-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doacao", models.BooleanField(default=False)),
                ("troca", models.BooleanField(default=False)),
                ("venda", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=250)),
                ("text", models.TextField(max_length=100000)),
                ("image", models.ImageField(blank=True, null=True, upload_to="post/")),
                ("data_postagem", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
