# Generated by Django 4.2.14 on 2024-08-11 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
