# Generated by Django 4.2.14 on 2024-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
