# Generated by Django 4.2.14 on 2024-09-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_rename_name_hashtag_title_post_archive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=3693),
        ),
    ]
