# Generated by Django 4.2.14 on 2024-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="Escreva sua bio...", max_length=100),
        ),
    ]
