# Generated by Django 4.2.14 on 2024-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_profile_name_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
