# Generated by Django 4.2.14 on 2024-08-15 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_profile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
