# Generated by Django 4.2.14 on 2024-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_remove_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
