# Generated by Django 4.2.14 on 2024-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saturday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sunday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thursday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tuesday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_evening_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_evening_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wednesday_night_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
