# Generated by Django 3.2.8 on 2023-01-25 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_maps', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='uploads/fotoperfil/')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='uploads/fotocapa/')),
                ('cor', models.CharField(default='#455A64', max_length=10)),
                ('contatos', models.ManyToManyField(related_name='_perfis_perfil_contatos_+', to='perfis.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacao', models.CharField(choices=[('VENDA', 'VENDA-Produto disponível para venda'), ('TROCA', 'TROCA-Produto disponível para troca'), ('DOAÇÃO', 'DOAÇÃO-Produto disponível para doação')], default='VENDA', max_length=10, verbose_name='Relação')),
                ('titulo', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/postagem/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='perfis.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfis.perfil')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='perfis.perfil')),
            ],
        ),
    ]
