# Generated by Django 3.2.8 on 2023-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relacao',
            field=models.CharField(choices=[('VENDA', 'VENDA - Alimento disponível para venda'), ('TROCA', 'TROCA - Alimento disponível para troca'), ('DOAÇÃO', 'DOAÇÃO - Alimento disponível para doação')], default='VENDA', max_length=10, verbose_name='Relação'),
        ),
    ]
